#!/usr/bin/env python3
"""
load_creds.py — Load credentials from secrets/creds.json into the environment.

Usage (Erebus-side):
    python3 scripts/load_creds.py [--env-file]

Reads secrets/creds.json and exports all values as environment variables
prefixed with the service name. For example:
    HF_TOKEN=hf_xxx
    COPERNICUS_USER=user
    AWS_ACCESS_KEY_ID=AKIA...

Use --env-file to write a .env file instead of exporting to current shell.

Run as: source <(python3 scripts/load_creds.py)
"""
import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CREDS = ROOT / "secrets" / "creds.json"


def is_placeholder(v):
    if not isinstance(v, str):
        return False
    s = v.strip()
    return s.startswith("FILL_ME_") or s.lower() == "skip" or s == ""


def load_creds():
    if not CREDS.exists():
        print(f"❌ {CREDS} not found", file=sys.stderr)
        sys.exit(1)
    return json.loads(CREDS.read_text())


def emit_export(creds, env_file=False):
    """Emit bash-style exports or env-file lines."""
    services = creds.get("services", {})
    n_loaded = 0
    n_skipped = 0
    lines = []
    lines.append("# Generated by load_creds.py — do not edit by hand")
    lines.append("# Source: secrets/creds.json")

    # Compute + hosting
    for k, v in creds.get("compute", {}).items():
        if not k.startswith("_") and not is_placeholder(v):
            env_key = f"COMPUTE_{k.upper()}"
            if env_file:
                lines.append(f'{env_key}="{v}"')
            else:
                lines.append(f"export {env_key}={shquote(v)}")
            n_loaded += 1

    for k, v in creds.get("hosting", {}).items():
        if not k.startswith("_") and not is_placeholder(v):
            env_key = f"HOSTING_{k.upper()}"
            if env_file:
                lines.append(f'{env_key}="{v}"')
            else:
                lines.append(f"export {env_key}={shquote(v)}")
            n_loaded += 1

    # Services
    for svc_name, svc_data in services.items():
        if not isinstance(svc_data, dict):
            continue
        priority = svc_data.get("_priority", "")
        for k, v in svc_data.items():
            if k.startswith("_"):
                continue
            if is_placeholder(v):
                n_skipped += 1
                continue
            # Build env var name
            env_key = f"{svc_name.upper()}_{k.upper()}"
            if env_file:
                lines.append(f'{env_key}="{v}"')
            else:
                lines.append(f"export {env_key}={shquote(v)}")
            n_loaded += 1

    return lines, n_loaded, n_skipped


def shquote(s):
    """Shell-quote a value for safe export."""
    if any(c in s for c in " \t\n\"'\\$;&|<>(){}*?[]"):
        return "'" + s.replace("'", "'\"'\"'") + "'"
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--env-file", action="store_true",
                    help="Write to .env file instead of stdout exports")
    ap.add_argument("--out", default=".env",
                    help="Output path when --env-file is set")
    args = ap.parse_args()

    creds = load_creds()
    lines, n_loaded, n_skipped = emit_export(creds, env_file=args.env_file)

    if args.env_file:
        out_path = Path(args.out)
        out_path.write_text("\n".join(lines) + "\n")
        out_path.chmod(0o600)
        print(f"✅ Wrote {out_path} ({n_loaded} vars, {n_skipped} skipped)")
        print(f"   File mode: 600 (owner-only)")
    else:
        print("\n".join(lines), file=sys.stdout)
        print(f"# Loaded {n_loaded} credentials, skipped {n_skipped}", file=sys.stderr)


if __name__ == "__main__":
    main()